# Generated by Django 4.2.1 on 2023-05-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_alter_cart_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='childrenproduct',
            name='img',
            field=models.ImageField(upload_to='Home/images'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='sizes',
            field=models.ManyToManyField(to='Home.size'),
        ),
    ]
