# Generated by Django 4.2.1 on 2023-05-19 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_size_alter_childrenproduct_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='babyproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('gender', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='Home/images')),
            ],
        ),
        migrations.CreateModel(
            name='babyAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.ManyToManyField(to='Home.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='baby_attributes', to='Home.babyproduct')),
                ('sizes', models.ManyToManyField(to='Home.size')),
            ],
        ),
    ]
